"use client";
import React, { useContext, useEffect, useState } from "react";
import { Button, Container, Modal, Offcanvas } from "react-bootstrap";
import main_logo from "../../app/assets/images/main-logo.svg";
import DarkMode from "../DarkMode/DarkMode";
import { RxHamburgerMenu } from "react-icons/rx";
import light_logo from "../../app/assets/images/footer_logo.png";
import { ThemeContext } from "@/ThemeProvider/ThemeProvider";
import close from "../../app/assets/images/close.png";
import Link from "next/link";

const Header = () => {
  const [show, setShow] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [iframeSrc, setIframeSrc] = useState("");

  const handleClose = () => setShow(false);
  const handleShow = (e) => {
    e.preventDefault();
    setShow(true);
  };
  const handleCloseModal = () => {
    setShowModal(false);
  };
  const handleShowModal = () => setShowModal(true);
  const { theme } = useContext(ThemeContext);
  // console.log(theme);

  useEffect(() => {
    if (showModal) {
      // Set the iframe src to reload the content when the modal opens
      setIframeSrc("https://app.pipefy.com/public/form/cHvjaOoc"); // Replace with your iframe URL
    }
  }, [showModal]);

  return (
    <div className='header'>
      <Container>
        <div className='d-flex align-items-center gap-60'>
          {theme === "dark" ? (
            <Link href='/'>
              <img
                style={{ width: "130px" }}
                src={light_logo.src}
                alt='main_logo'
              />
            </Link>
          ) : (
            <Link href='/'>
              <img
                style={{ width: "130px" }}
                src={main_logo.src}
                alt='main_logo'
              />
            </Link>
          )}
          {/* <img src={main_logo.src} alt='main_logo' /> */}
          <ul className='main_menu d-none d-lg-block'>
            <li>
              <a href=''>Explore</a>
            </li>
          </ul>
        </div>
        <div className='d-flex align-items-center gap-4'>
          <DarkMode></DarkMode>
          <div
            className=' d-lg-none cursor-pointer hambuger'
            onClick={handleShow}
          >
            <RxHamburgerMenu />
          </div>
          <button
            onClick={handleShowModal}
            className='thm_btn d-none d-lg-block'
          >
            <a href='#'>Contact Us</a>
          </button>
        </div>
        <Offcanvas show={show} onHide={handleClose}>
          <Offcanvas.Header closeButton>
            <Offcanvas.Title>
              <img
                style={{ width: "130px" }}
                src={main_logo.src}
                alt='main_logo'
              />
            </Offcanvas.Title>
          </Offcanvas.Header>
          <Offcanvas.Body>
            <ul className='main_menu'>
              <li>
                <a href='#'>Explore</a>
              </li>
            </ul>
            <button
              onClick={() => {
                handleClose();
                handleShowModal();
              }}
              className='thm_btn '
              style={{ marginTop: "10px" }}
            >
              <a href='#'>Contact Us</a>
            </button>
          </Offcanvas.Body>
        </Offcanvas>
        <Modal
          show={showModal}
          onHide={handleCloseModal}
          backdrop='static'
          keyboard={false}
        >
          <Modal.Header>
            <img
              style={{ marginLeft: "auto", cursor: "pointer" }}
              onClick={handleCloseModal}
              src={close.src}
              alt=''
            />
          </Modal.Header>
          <Modal.Body>
            <iframe src={iframeSrc} frameborder='0'></iframe>

            {/* <form action=''>
              <div className=''>
                <label htmlFor=''>Full Name*</label>
                <input type='text' placeholder='Enter your name' />
              </div>
              <div className=''>
                <label htmlFor=''>Email Address*</label>
                <input type='email' placeholder='Enter your email' />
              </div>
              <div className=''>
                <label htmlFor=''>Phone Number*</label>
                <input type='number' placeholder='Enter your phone number' />
              </div>
              <div className=''>
                <input className='thm_btn' type='submit' value='Contact Us' />
              </div>
            </form>
            <p className='desc'>
              Never submit passwords or sensitive data through unknown forms.
              Make sure this form was generated by your company or a trusted
              company.
            </p> */}
          </Modal.Body>
        </Modal>
      </Container>
    </div>
  );
};

export default Header;
