"use client";
import { useEffect, useState } from "react";
import { Col, Container, Row, Modal } from "react-bootstrap";
import background_image from "../../app/assets/images/banner-img.png";
import b_chart from "../../app/assets/images/B.png";
import axios from "axios";
import close from "../../app/assets/images/close.png";

const Banner = () => {
  const [showModal, setShowModal] = useState(false);
  const [iframeSrc, setIframeSrc] = useState("");
  const handleCloseModal = () => {
    setShowModal(false);
  };
  const handleShowModal = () => setShowModal(true);
  useEffect(() => {
    if (showModal) {
      // Set the iframe src to reload the content when the modal opens
      setIframeSrc("https://app.pipefy.com/public/form/cHvjaOoc"); // Replace with your iframe URL
    }
  }, [showModal]);
  return (
    <div className='banner'>
      <Container>
        <Row>
          <Col xs={12} lg={7}>
            <div className='banner_content'>
              <h1>
                The <span>Solution</span> for Automated DeFi Yield Strategies{" "}
                <span>
                  <img src={b_chart.src} alt='' />
                </span>
              </h1>
              <p>Empowering Your DeFi Yield Automation</p>
              <button onClick={handleShowModal} className='thm_btn talk_btn'>
                <a href='#'>Talk to Us</a>
              </button>
            </div>
          </Col>
          <Col xs={12} lg={5} className='position-relative'>
            <img
              className='banner_image top-left'
              src={background_image.src}
              alt=''
            />
          </Col>
        </Row>
        <Modal
          show={showModal}
          onHide={handleCloseModal}
          backdrop='static'
          keyboard={false}
        >
          <Modal.Header>
            <img
              style={{ marginLeft: "auto", cursor: "pointer" }}
              onClick={handleCloseModal}
              src={close.src}
              alt=''
            />
          </Modal.Header>
          <Modal.Body>
            <iframe src={iframeSrc} frameborder='0'></iframe>

            {/* <form action=''>
              <div className=''>
                <label htmlFor=''>Full Name*</label>
                <input type='text' placeholder='Enter your name' />
              </div>
              <div className=''>
                <label htmlFor=''>Email Address*</label>
                <input type='email' placeholder='Enter your email' />
              </div>
              <div className=''>
                <label htmlFor=''>Phone Number*</label>
                <input type='number' placeholder='Enter your phone number' />
              </div>
              <div className=''>
                <input className='thm_btn' type='submit' value='Contact Us' />
              </div>
            </form>
            <p className='desc'>
              Never submit passwords or sensitive data through unknown forms.
              Make sure this form was generated by your company or a trusted
              company.
            </p> */}
          </Modal.Body>
        </Modal>
      </Container>
    </div>
  );
};

export default Banner;
